config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :facilities
  resources :staffs
  resources :monsters
get 'scp', to: 'scp#index'
  get 'scp/show'
  get 'scp/create'
  post 'scp/new'
  get 'scp/edit'
  post 'scp/update'
  get 'scp/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  acts_as_token_authentication_handler_for User
  before_action :set_staff, only: [:show, :edit, :update, :destroy] 
  skip_before_action :verify_authenticity_token 


  # GET /staffs
  # GET /staffs.json
  def index
    id = params[:id]
    @staffs = pagination("staffs", "staffs.name")
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    id = params[:id]

    query = " SELECT staffs.id, staffs.age, staffs.name, staffs.positionId, 
      sc.Name AS SecurityClearance, pc.PositionName AS PositionClearance, f.name as FacilityName, staffs.facilityId 
              FROM staffs
              INNER JOIN PositionClearance pc ON pc.PositionId = staffs.positionId
              INNER JOIN SecurityClearance sc ON sc.Level = pc.ClearanceLevel
	            INNER JOIN facilities f ON f.Id = staffs.facilityId
              WHERE staffs.id = ?;"

    vals = [[nil, id]]
    @staff = ActiveRecord::Base.connection.exec_insert(query, "show", vals)[0]
    puts @staff

    if(params[:api])
      render json: { 
             "name" => @staff["name"],
             "age" => @staff["age"],
             "PositionClearance" => @staff["PositionClearance"],
	     "FacilityName" => @staff["FacilityName"]
          }.to_json, status: 200
      return
    end

  end

  # GET /staffs/new
  def new
    @staff = Staff.new
    facility_query = "SELECT id, name FROM facilities;"
    @facilities = ActiveRecord::Base.connection.execute(facility_query)
    position_query = "SELECT * FROM PositionClearance;"
    @positions = ActiveRecord::Base.connection.execute(position_query)
  end

  # GET /staffs/1/edit
  def edit
    facility_query = "SELECT id, name FROM facilities;"
    @facilities = ActiveRecord::Base.connection.execute(facility_query)
    position_query = "SELECT * FROM PositionClearance;"
    @positions = ActiveRecord::Base.connection.execute(position_query)
  end

  # POST /staffs
  # POST /staffs.json
  def create
   if(params["api"])
      name = params[:name]
      age = params[:age]
      position = params[:position]
    else
      name = params[:staff][:name]
      age = params[:staff][:age]
      position = params[:position]
    end
    
    # query = "INSERT INTO staffs(name, age, position, created_at, updated_at) VALUES('" + name +  "',"+ age +",'"+ position +"', '', '')"
    query = "INSERT INTO staffs(name, age, positionId, FacilityId) VALUES(?, ?, ?, ?)"
    # vals = [ActiveRecord::Relation::QueryAttribute.new("String", name, Type::Value.new), Relation::QueryAttribute.new("number", age, Type::Value.new), 
    #   Relation::QueryAttribute.new("String", position, Type::Value.new)]
    vals = [[nil, name], [nil, age], [nil, position], [nil, params["facility"]]]
    result = ActiveRecord::Base.connection.exec_insert(query, "insert", vals)
    if(params["api"])
      head :created, location: "Somewhere"
      return
    else
      redirect_to staffs_path()
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    id = params[:id]
    if(params["api"])
      name = params["name"]
      age = params["age"].to_i
      position = params["position"].to_i
    else
      name = params[:staff][:name]
      age = params[:staff][:age]
      position = params[:position]
    end
    
        query = "UPDATE staffs SET name = ?, age = ?, positionId = ?, FacilityId = ? WHERE id = ?;"
    # vals = [ActiveRecord::Relation::QueryAttribute.new("String", name, Type::Value.new), Relation::QueryAttribute.new("number", age, Type::Value.new), 
    #   Relation::QueryAttribute.new("String", position, Type::Value.new)]
    vals = [[nil, name], [nil, age], [nil, position], [nil, params["facility"].to_i], [nil, id]]
    result = ActiveRecord::Base.connection.exec_update(query, "update", vals)
    if(params["api"])
      head :updated, location: "Somewhere"
      return
    else
      redirect_to staffs_path()
    end

  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy

    if(params["api"])
      id = params[:id]
    else
      id = @staff.id
    end
    query = "DELETE FROM staffs WHERE id = ?;"
    # vals = [ActiveRecord::Relation::QueryAttribute.new("String", name, Type::Value.new), Relation::QueryAttribute.new("number", age, Type::Value.new), 
    #   Relation::QueryAttribute.new("String", position, Type::Value.new)]
    vals = [[nil, params["id"]]]
    result = ActiveRecord::Base.connection.exec_delete(query, "insert", vals)

    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :age, :positionId)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <!-- <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div> -->
  <p>Position: </p>
  <% for position in @positions %>
    <%= radio_button_tag(:position, position["PositionId"]) %>
    <%= label_tag(:position, position["PositionName"], style: "display: inline") %>
  <% end %>

  <p>Working at facility: </p>
  <% for facility in @facilities %>
    <%= radio_button_tag(:facility, facility["id"]) %>
    <%= label_tag(:facility, facility["name"], style: "display: inline") %>
  <% end %>
  
  <br><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= form_for @staff do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <p>Position: </p>
  <% for position in @positions %>
    <%= radio_button_tag(:position, position["PositionId"]) %>
    <%= label_tag(:position, position["PositionName"], style: "display: inline") %>
  <% end %>

  <p>Working at facility: </p>
  <% for facility in @facilities %>
    <%= radio_button_tag(:facility, facility["id"]) %>
    <%= label_tag(:facility, facility["name"], style: "display: inline") %>
  <% end %>

    <%= f.hidden_field :original_name, value:@staff.name %>
    <%= hidden_field_tag 'selected', 'none'  %>

    <%= f.submit 'Continue', class: 'button' %>
<% end %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff["name"] %></td>
        <td><%= staff["age"] %></td>
        <td><%= staff["positionId"] %></td>
        <td><%= link_to 'Show', "/staffs/" + staff["id"].to_s %></td>
        <td><%= link_to 'Edit', "/staffs/" + staff["id"].to_s + "/edit" %></td>
        <td><%= link_to 'Destroy', "/staffs/" + staff["id"].to_s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<%= button_to "Prev", staffs_path(), method: :get, params:  {"page": [@page-1, 0].max, "limit": @limit} %>
<%= @page + 1 %> / <%= @total_pages %>
<%= button_to "Next", staffs_path(), method: :get, params:  {"page": [@page+1, @total_pages-1].min,"limit": @limit}%>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @staff["name"] %>
</p>
<p>
  <strong>Clearance Level:</strong>
  <%= @staff["SecurityClearance"] %>
</p>

<p>
  <strong>Clearance Rank:</strong>
  <%= @staff["positionId"] %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff["PositionClearance"] %>
</p>


<p>
  <strong>Facility:</strong>
  <%= link_to @staff["FacilityName"], controller: "facilities", action: "show", id: @staff["FacilityId"] %>

</p>



<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>