config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :facilities
  resources :staffs
  resources :monsters
get 'scp', to: 'scp#index'
  get 'scp/show'
  get 'scp/create'
  post 'scp/new'
  get 'scp/edit'
  post 'scp/update'
  get 'scp/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  # acts_as_token_authentication_handler_for User, fallback: :permission_denied
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /facilities
  # GET /facilities.json

  def permission_denied
    redirect_to(root_path, status: 401)
  end

  def index
    id = params[:id]
    @facilities = pagination("facilities", "facilities.Name")
      if(params[:api])
        js = []
        @facilities.each do |fac|
          puts fac
          js.push(
            { 
                 "name" => fac["name"],
                 "capacity" => fac["capacity"],
                 "Id" => fac["id"]
              })
          
          
        end
        render json: { 
                 "facilities" => js
              }.to_json, status: 200
    end
      # puts @facilities[0]["id"]
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    id = params[:id]
    query = "SELECT fac.name, fac.capacity, ac.Name as AnomalyClass 
             FROM facilities fac
             INNER JOIN AnomalyClass ac ON ac.Id = fac.ClassId
             WHERE fac.Id = ?"

    vals = [[nil, id]]
    @facility = ActiveRecord::Base.connection.exec_insert(query, "show", vals)[0]
    query = "SELECT sc.Id, sc.Name 
             FROM SCP sc
             INNER JOIN facilities fac ON fac.Id = sc.FacilityContainedId
             WHERE fac.Id = ?"
    @scps = ActiveRecord::Base.connection.exec_query(query, "scp query", vals)
    # @staff = []

    query = "SELECT st.name, st.id
             FROM staffs st
             INNER JOIN facilities fac ON fac.Id = st.FacilityId
             WHERE fac.Id = ?"
   @staff = ActiveRecord::Base.connection.exec_query(query, "staff query", vals)

   if(params[:api])
      render json: { 
             "name" => @facility["name"],
             "capacity" => @facility["capacity"],
             "Anomaly class" => @facility["AnomalyClass"],
             "scps" => @scps.map { |sc| sc["Name"] },
             "staff" => @staff.map { |st| st["name"]}
          }.to_json, status: 200
      return
    end

  end

  # GET /facilities/new
  def new
    @facility = Facility.new
    class_query = "SELECT Id, Name FROM AnomalyClass;"
    @anomaly_classes = ActiveRecord::Base.connection.execute(class_query)
  end

  # GET /facilities/1/edit
  def edit
    clearance_query = "SELECT Level, Name FROM SecurityClearance;"
    @clearance_levels = ActiveRecord::Base.connection.execute(clearance_query)

    class_query = "SELECT Id, Name FROM AnomalyClass;"
    @anomaly_classes = ActiveRecord::Base.connection.execute(class_query)

    facility_query = "SELECT id, name FROM facilities;"
    @facilities = ActiveRecord::Base.connection.execute(facility_query)
  end

  # POST /facilities
  # POST /facilities.json
  def create
    if(params["api"])
      name = params[:name]
      capacity = params[:capacity]
      anomaly_class = params[:anomaly_class]
    else
      name = params[:facility][:name]
      capacity = params[:facility][:capacity]
      anomaly_class = params[:anomaly_class]
    end
    # query = "INSERT INTO staffs(name, age, position, created_at, updated_at) VALUES('" + name +  "',"+ age +",'"+ position +"', '', '')"
      query = "INSERT INTO facilities(id, name, capacity, ClassId) VALUES(NULL, ?, ?, ?)"
      # vals = [ActiveRecord::Relation::QueryAttribute.new("String", name, Type::Value.new), Relation::QueryAttribute.new("number", age, Type::Value.new), 
      #   Relation::QueryAttribute.new("String", position, Type::Value.new)]
      vals = [[nil, name], [nil, capacity], [nil, anomaly_class]]
    result = ActiveRecord::Base.connection.exec_insert(query, "insert facility", vals)
    query = "SELECT last_insert_rowid() as last" 
    id = ActiveRecord::Base.connection.exec_query(query, "insert facility", [])
    id_to_return = id[0]["last"]
    ur = request.original_url
    if(params["api"])
      head :created, location: ur[0, ur.index("?")] + "/" + id_to_return.to_s
      return
    else
      redirect_to facilities_path()
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update # add anomaly class update
    id = params[:id]
    anomaly_class = params["anomaly_class"]
    if(params["api"])
      name = params[:name]
      capacity = params[:capacity]
    else
    name = params[:facility][:name]
    capacity = params[:facility][:capacity]
      
    end
    query = "UPDATE facilities SET name=?, ClassId=?, capacity=? where id = ?;"
    vals = [[nil, name], [nil, anomaly_class], [nil, capacity],  [nil, id]]
    result = ActiveRecord::Base.connection.exec_update(query, "update facility", vals)
    if(params["api"])
      head :ok
      return
    else
      redirect_to facility_path(id)
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    if(params["api"])
      id = params[:id]
    else
      id = @facility.id
    end
    query = "DELETE FROM facilities WHERE id = ?;"
    vals = [[nil, id]]
    result = ActiveRecord::Base.connection.exec_delete(query, "delete facility", vals)
    if(params["api"])
      head :ok
      return
    end
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :capacity)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_with(model: facility, local: true) do |form| %>
  <% if facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <p>Anomaly class:</p>
  <% for anomaly_class in @anomaly_classes %>
    <%= radio_button_tag(:anomaly_class, anomaly_class["Id"]) %>
    <%= label_tag(:anomaly_class, anomaly_class["Name"], style: "display: inline") %>
    <br>
  <% end %>
  <br>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility["name"] %></td>
        <td><%= facility["capacity"] %></td>
        <td><%= link_to 'Show', "/facilities/" + facility["id"].to_s %></td>
        <td><%= link_to 'Edit', "/facilities/" + facility["id"].to_s + "/edit/" %></td>
        <td><%= link_to 'Destroy', "/facilities/" + facility["id"].to_s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_facility_path %>

<%= button_to "Prev", facilities_path(), method: :get, params:  {"page": [@page-1, 0].max, "limit": @limit} %>
<%= @page + 1 %> / <%= @total_pages %>
<%= button_to "Next", facilities_path(), method: :get, params:  {"page": [@page+1, @total_pages-1].min,"limit": @limit}%>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facility["name"] %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @facility["capacity"] %>
</p>

<p>
  <strong>Anomaly Type:</strong>
  <%= @facility["AnomalyClass"] %>
</p>

<p>
  <strong>SCPs:</strong>
  <tbody>
	<% @scps.each do |scp| %>
	  <tr>
	  	
	    <td><%= link_to scp["Name"], controller: "scp", action: "show", id: scp["Id"] %></td>
	  </tr>
	  <br>
	<% end %>
</tbody>
</p>

<p>
  <strong>Staff:</strong>
  <tbody>
	<% @staff.each do |staff| %>
	  <tr>
	  	<%= link_to staff["name"], controller: "staffs", action: "show", id: staff["id"] %>
	  <br>
	<% end %>
</tbody>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>