config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :facilities
  resources :staffs
  resources :monsters
get 'scp', to: 'scp#index'
  get 'scp/show'
  get 'scp/create'
  post 'scp/new'
  get 'scp/edit'
  post 'scp/update'
  get 'scp/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/scp_controller.rb
class ScpController < ApplicationController
  def index
    id = params[:id]
    @scps = pagination("SCP", "SCP.Name")
  end


  def show
    id = params[:id]

    query = " SELECT 
              scp.Id, scp.Name, scp.Description, sc.Name AS SecurityClearance, ac.Name as AnomalyClass,
              f.name AS FacilityName, f.id AS FacilityId

              FROM SCP scp
              LEFT JOIN SecurityClearance sc ON sc.Level = scp.SecurityClearanceNeeded
              LEFT JOIN AnomalyClass ac ON ac.Id = scp.ClassId
              LEFT JOIN facilities f ON f.id = scp.FacilityContainedId
              WHERE scp.Id = ?;"

    vals = [[nil, id]]

    @scp = ActiveRecord::Base.connection.exec_insert(query, "show", vals)[0]
  end


  def new
    name = params[:name]
    description = params[:description]
    clearance_level = params[:clearance_level]
    anomaly_class = params[:anomaly_class]
    facility = params[:facility]

    if facility and is_facility_full(facility)
        redirect_to controller: "scp", action: "create"
        return
    end

    query = " INSERT INTO SCP(Name, Description, SecurityClearanceNeeded, ClassId, FacilityContainedId)
              VALUES(?, ?, ?, ?, ?)"

    vals = [[nil, name], [nil, description], [nil, clearance_level], [nil, anomaly_class], [nil, facility]]

    begin
      ActiveRecord::Base.connection.exec_insert(query, "create", vals)
      redirect_to controller: "scp", action: "index"
    rescue ActiveRecord::NotNullViolation => e
      redirect_to controller: "scp", action: "create"
    end
    
  end

  def is_facility_full(facility)
    facility_count = "SELECT f.capacity as FacilityCapacity, COUNT(scp.Name) as SCPCount
                FROM facilities f
                LEFT JOIN SCP scp ON scp.FacilityContainedId = f.id
                WHERE f.id = ?;"

    vals = [[nil, facility]]
    facility_info = ActiveRecord::Base.connection.exec_query(facility_count, "facility_info", vals)[0]
    print("faclity id " + facility)
    print(facility_info )
    return facility_info["SCPCount"] >= facility_info["FacilityCapacity"]
  end


  def create

    clearance_query = "SELECT Level, Name FROM SecurityClearance;"
    @clearance_levels = ActiveRecord::Base.connection.execute(clearance_query)

    class_query = "SELECT Id, Name FROM AnomalyClass;"
    @anomaly_classes = ActiveRecord::Base.connection.execute(class_query)

    facility_query = "SELECT id, name FROM facilities;"
    @facilities = ActiveRecord::Base.connection.execute(facility_query)
  end

  def edit
    clearance_query = "SELECT Level, Name FROM SecurityClearance;"
    @clearance_levels = ActiveRecord::Base.connection.execute(clearance_query)

    class_query = "SELECT Id, Name FROM AnomalyClass;"
    @anomaly_classes = ActiveRecord::Base.connection.execute(class_query)

    facility_query = "SELECT id, name FROM facilities;"
    @facilities = ActiveRecord::Base.connection.execute(facility_query)

    id = params[:id]


    query = " SELECT 
              scp.Id, scp.Name, scp.Description, scp.SecurityClearanceNeeded, scp.ClassId, scp.FacilityContainedId 
              FROM SCP
              WHERE scp.Id = ?;"

    vals = [[nil, id]]

    @scp = ActiveRecord::Base.connection.exec_insert(query, "update", vals)[0]
  end


  def update
    id = params[:id]
    name = params[:name]
    description = params[:description]
    clearance_level = params[:clearance_level]
    anomaly_class = params[:anomaly_class]
    facility = params[:facility]

    

    query = " UPDATE SCP
              SET 
              Name = ?,
              Description = ?,
              SecurityClearanceNeeded = ?,
              ClassId = ?,
              FacilityContainedId = ?
              WHERE Id = ?"

    vals = [
      [nil, name], [nil, description], [nil, clearance_level], [nil, anomaly_class], [nil, facility],[nil, id]
    ]

    begin
      ActiveRecord::Base.connection.exec_insert(query, "create", vals)
      redirect_to controller: "scp", action: "show", id: id
    rescue ActiveRecord::NotNullViolation => e
      redirect_to controller: "scp", action: "edit", id: id
    end
  end


  def destroy
    id = params[:id]

    query = "DELETE FROM SCP WHERE Id = ?;"
    vals = [[nil, id]]
    ActiveRecord::Base.connection.exec_insert(query, "destroy", vals)

    redirect_to controller: "scp", action: "index"
  end
end

app/helpers/scp_helper.rb
module ScpHelper
end

app/views/scp/create.html.erb
<%= form_tag(controller: "scp", action: "new", method: "post") do %>
	<%= label_tag(:name, "Name: ") %>
	<%= text_field_tag(:name) %>
	<br><br>

	<%= label_tag(:description, "Description: ") %>
	<%= text_area_tag(:description) %>

	<p>Anomaly class:</p>
	<% for anomaly_class in @anomaly_classes %>
		<%= radio_button_tag(:anomaly_class, anomaly_class["Id"]) %>
		<%= label_tag(:anomaly_class, anomaly_class["Name"], style: "display: inline") %>
		<br>
	<% end %>

	<br>
	
	<p>Security clearance needed:</p>
	<% for clearance_level in @clearance_levels %>
		<%= radio_button_tag(:clearance_level, clearance_level["Level"]) %>
		<%= label_tag(:clearance_level, clearance_level["Name"], style: "display: inline") %>
		<br>
	<% end %>

	<br>

	<p>Facilities: </p>
	<% for facility in @facilities %>
		<%= radio_button_tag(:facility, facility["id"]) %>
		<%= label_tag(:facility, facility["name"], style: "display: inline") %>
	<% end %>
	
	<br><br>
	
	<%= submit_tag("submit") %>

<% end %>

<br><br>
<%= link_to 'Back', controller: "scp", action: "index" %>

app/views/scp/destroy.html.erb
<h1>Scp#destroy</h1>
<p>Find me in app/views/scp/destroy.html.erb</p>

app/views/scp/edit.html.erb
<%= form_tag(controller: "scp", action: "update", method: "post") do %>
	<%= label_tag(:name, "Name: ") %>
	<%= text_field_tag(:name, @scp["Name"]) %>
	<br><br>

	<%= label_tag(:description, "Description: ") %>
	<%= text_area_tag(:description, @scp["Description"]) %>

	<p>Anomaly class:</p>
	<% for anomaly_class in @anomaly_classes %>
		<% if @scp["ClassId"] == anomaly_class["Id"] %>
			<%= radio_button_tag(:anomaly_class, anomaly_class["Id"], true) %>
		<% else %>
			<%= radio_button_tag(:anomaly_class, anomaly_class["Id"]) %>
		<% end %>
		<%= label_tag(:anomaly_class, anomaly_class["Name"], style: "display: inline") %>
		<br>
	<% end %>

	<br>
	
	<p>Security clearance needed:</p>
	<% for clearance_level in @clearance_levels %>
		<% if @scp["SecurityClearanceNeeded"] == clearance_level["Level"] %>
			<%= radio_button_tag(:clearance_level, clearance_level["Level"], true) %>
		<% else %>
			<%= radio_button_tag(:clearance_level, clearance_level["Level"]) %>
		<% end %>
		<%= label_tag(:clearance_level, clearance_level["Name"], style: "display: inline") %>
		<br>
	<% end %>

	<p>Facilities: </p>
	<% for facility in @facilities %>
		<% if @scp["FacilityContainedId"] == facility["id"] %>
			<%= radio_button_tag(:facility, facility["id"], true) %>
		<% else %>
			<%= radio_button_tag(:facility, facility["id"]) %>
		<% end %>
		<%= label_tag(:facility, facility["name"], style: "display: inline") %>
	<% end %>
	
	<br><br>

	<%= hidden_field_tag(:id, @scp["Id"]) %>
	<br>

	<%= submit_tag("Edit") %>

<% end %>

<br><br>
<%= link_to 'Back', controller: "scp", action: "index" %>

app/views/scp/index.html.erb
<tbody>
<% @scps.each do |scp| %>
  <tr>
  	<%= scp["Name"] %>
    <td><%= link_to 'Show', controller: "scp", action: "show", id: scp["Id"] %></td>
    <td><%= link_to 'Edit', controller: "scp", action: "edit", id: scp["Id"] %></td>
    <td><%= link_to 'Destroy', controller: "scp", action: "destroy", id: scp["Id"] %></td>
  </tr>
  <br>
<% end %>
</tbody>

<br>
<%= link_to 'New SCP', controller: "scp", action: "create" %>

<%= button_to "Prev", scp_path(), method: :get, params:  {"page": [@page-1, 0].max, "limit": @limit} %>
<%= @page + 1 %> / <%= @total_pages %>
<%= button_to "Next", scp_path(), method: :get, params:  {"page": [@page+1, @total_pages-1].min,"limit": @limit}%>

app/views/scp/show.html.erb
<p><%= @scp["Name"] %></p>
<% if @scp["SecurityClearance"] %>
	<p>Clearance: <%= @scp["SecurityClearance"] %></p>
<% end %>

<% if @scp["AnomalyClass"] %>
	<p>Classification: <%= @scp["AnomalyClass"] %></p>
<% end %>

<% if @scp["FacilityName"] %>
	<p>Contained in facility: <%= link_to @scp["FacilityName"], controller: "facilities", action: "show", id: @scp["FacilityId"] %></p>
<% end %>
<br>
<p><%= @scp["Description"] %></p>

<%= link_to 'Back', controller: "scp", action: "index" %>